version: "3.9"

services:
  backend:
    container_name: koombea_nodejs
    restart: always
    build:
      context: .
    ports:
      - "3000:3000"
      - "9229:9229"
    command: tail -f /dev/null
    volumes:
      - ./:/app
      - ./node_modules:/app/node_modules
    depends_on:
      - pgsql

  pgsql:
    image: 'postgres:13'
    ports:
      - '${FORWARD_DB_PORT:-5432}:5432'
    environment:
      PGPASSWORD: '${DB_PASSWORD:-secret}'
      POSTGRES_DB: '${DB_DATABASE}'
      POSTGRES_USER: '${DB_USERNAME}'
      POSTGRES_PASSWORD: '${DB_PASSWORD:-secret}'
    volumes:
      - 'koombeanodejspgsql:/var/lib/postgresql/data'
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "${DB_DATABASE}", "-U", "${DB_USERNAME}"]
      retries: 3
      timeout: 5s

volumes:
  koombeanodejspgsql:
